# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13652e2f5db66a384005344be221a192f53aac53fc8f63c4e80a36d4790bfed4c9b12b4942d858876bb43032374f09bb2ae32dd7ec33a03b2211d5a65a51ccf6

test:
  secret_key_base: 3c48988b846cbbbff0d05336ac917007e678c68b3e5763c679550ff4fe3e3cfced11c5bda94c296fb1df7b724f58db7c44e5ddd44344516018ba946cfe99858a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
